### ISSUE TITLE
Lab 06: Column is unknown

### ISSUE THREAD

**Issue by ecking** [DS4PS/cpp-526-spr-2020#25]
I know this is a novice question but I haven't a clue as to why I'm receiving the error that column "playerID" is unknown. Suggestions?

`Salaries %>%
  group_by(teamID, yearID)%>%
  summarize(total_salary = sum(salary.adj))%>%
  count(playerID)`

**Comment by jamisoncrawford** [comment]
Not novice at all!

When you use `group_by()` and `summarize()`, your output will only be the variables by which you've grouped as well as the new summary variables you've created.

Because you've not grouped by `playerID`, it won't appear in your output and won't be detectable in downstream piping.

However, you can take your summary variables and rejoin them by adding:

```
%>%
right_join(Salaries)
```

This will duplicate your `summarize()` output along matching values as long as `Salaries` and your output have one column/variable in common.

I've literally just published a new video on this (seconds ago) and have yet to add bookmarks - it won't be available in high definition for a few more minutes, but you can find it here:

https://www.youtube.com/watch?v=578GmqHqoJ4&feature=youtu.be

This provides an overview as to why `summarize()` drops variables and how you can rejoin them to your original data.  Hope this helps!
